package com.example.security3.enums;

public enum ErrorCode {
    GENERAL,
    USER_NOT_FOUND,
    EMPLOYEE_NOT_FOUND,
    USER_DUPLICATE,
    EMPLOYEE_DUPLICATE,
    BAD_REQUEST,
    NOT_FOUND,
    PHONE_NUMBER_DUPLICATE,
    PRODUCT_NOT_FOUND,
    ID_SPECIFIED,
    ID_NOT_SPECIFIED,
    PRODUCT_WAREHOUSE_NOT_FOUND,
    NOT_ENOUGH_PRODUCT,
    MATERIAL_NOT_FOUND,
    FILE_NOT_SAVE, CLIENT_NOT_FOUND,
    MEASUREMENT_NOT_FOUND,

    SUPPLIER_NOT_FOUND,
}
